[general]
fullscreen = false
initial-tool = "line"
copy-command = "wl-copy"
output-filename = "/home/rrossamakhin/places/sys/satty-%Y-%m-%d_%H:%M:%S.png"
disable-notifications = true

# Font to use for text annotations
[font]
family = "Roboto"
style = "Bold"

[color-palette]
first= "#ff0000"
second= "#ffe100"
third= "#00ff00"
