[font]
size = 11.5

[env]
TERM = "xterm-256color"

[shell]
program = "/usr/bin/tmux"

[font.normal]
family = "terminal-font"

[mouse]
hide_when_typing = true

[colors.primary]
background = '#2b2b2b'
foreground = '#d1d5da'

# Normal colors
[colors.normal]
black   = '#586069'
red     = '#ea4a5a'
green   = '#34d058'
yellow  = '#ffea7f'
blue    = '#2188ff'
magenta = '#b392f0'
cyan    = '#39c5cf'
white   = '#d1d5da'

# Bright colors
[colors.bright]
black   = '#959da5'
red     = '#f97583'
green   = '#85e89d'
yellow  = '#ffea7f'
blue    = '#79b8ff'
magenta = '#b392f0'
cyan    = '#56d4dd'
white   = '#fafbfc'
