[font]
size = 11.5

[shell]
program = "/usr/bin/tmux"

[font.normal]
family = "JetBrainsMonoNerdFont"
style = "Medium"

[mouse]
hide_when_typing = true

[colors.primary]
foreground = "#ffffff"
background = "#1E1E1E"

[colors.normal]
black = "#1d1f21"
white = "#c5c8c6"
red = "#cc6666"
green = "#b5bd68"
yellow = "#f0c674"
blue = "#81a2be"
magenta = "#b294bb"
cyan  = "#8abeb7"

[colors.bright]
black = "#373b41"
white = "#eaeaea"
red = "#d54e53"
green = "#b9ca4a"
yellow = "#e7c547"
blue = "#7aa6da"
magenta = "#c397d8"
cyan = "#70c0b1"
